import type { Driver } from "./db";
import { computeScores, SCORE_VERSION } from "./scoring";
import type { ProductData } from "./types";

// ============================================================
// Basisprodukte für den Erststart. Fiktive Marken mit realistischen
// Werten — sie machen die App ab Sekunde 1 demonstrierbar und dienen
// als Alternativen-Pool, bis echte Scans die Datenbank füllen.
// ============================================================

const P = (p: ProductData) => p;

export const SEED_PRODUCTS: ProductData[] = [
  P({
    barcode: "4012345678901",
    name: "Bio Haferflocken",
    brand: "Naturkind",
    quantity: "500 g",
    category: "cereals",
    ingredientsText: "Hafervollkornflocken* (100 %). *aus kontrolliert ökologischem Anbau",
    ingredients: [{ name: "Hafervollkornflocken", percent: 100 }],
    nutriments: { energyKcal: 372, fat: 7, satFat: 0.8, carbs: 58.7, sugars: 1.2, protein: 13.5, salt: 0.01, fiber: 10 },
    additives: [],
    allergens: ["gluten"],
    labels: ["organic"],
    analysisTags: ["vegan", "vegetarian", "palm-oil-free"],
    originCountry: "de",
    packaging: ["cardboard"],
    novaGroup: 1,
  }),
  P({
    barcode: "4012345678918",
    name: "Haferflocken Zart",
    brand: "Goldkorn",
    quantity: "500 g",
    category: "cereals",
    ingredientsText: "Hafervollkornflocken (100 %)",
    ingredients: [{ name: "Hafervollkornflocken", percent: 100 }],
    nutriments: { energyKcal: 370, fat: 7, satFat: 1.3, carbs: 59, sugars: 0.7, protein: 13, salt: 0.02, fiber: 10 },
    additives: [],
    allergens: ["gluten"],
    labels: [],
    analysisTags: ["vegan", "vegetarian", "palm-oil-free"],
    originCountry: "de",
    packaging: ["cardboard"],
    novaGroup: 1,
  }),
  P({
    barcode: "4012345679021",
    name: "Glutenfreie Haferflocken",
    brand: "Naturkind",
    quantity: "475 g",
    category: "cereals",
    ingredientsText: "Glutenfreie Hafervollkornflocken* (100 %). *aus kontrolliert ökologischem Anbau",
    ingredients: [{ name: "Glutenfreie Hafervollkornflocken", percent: 100 }],
    nutriments: { energyKcal: 373, fat: 7.1, satFat: 1.2, carbs: 59, sugars: 1.1, protein: 13, salt: 0.01, fiber: 9.7 },
    additives: [],
    allergens: [],
    labels: ["organic", "gluten-free"],
    analysisTags: ["vegan", "vegetarian", "palm-oil-free"],
    originCountry: "de",
    packaging: ["cardboard"],
    novaGroup: 1,
  }),
  P({
    barcode: "4012345678925",
    name: "Schoko-Knusper-Müsli",
    brand: "Morgenglück",
    quantity: "750 g",
    category: "cereals",
    ingredientsText:
      "Vollkorn-Haferflocken (48 %), Zucker, Schokoladenstückchen (12 %) (Kakaomasse, Zucker, Kakaobutter, Emulgator: Sojalecithine), Palmöl, Glukosesirup, Kakaopulver (2 %), Salz, Aroma",
    ingredients: [
      { name: "Vollkorn-Haferflocken", percent: 48 },
      { name: "Zucker" },
      { name: "Schokoladenstückchen", percent: 12 },
      { name: "Palmöl" },
      { name: "Glukosesirup" },
      { name: "Kakaopulver", percent: 2 },
      { name: "Salz" },
      { name: "Aroma" },
    ],
    nutriments: { energyKcal: 447, fat: 14, satFat: 5.2, carbs: 64, sugars: 22, protein: 9, salt: 0.25, fiber: 7 },
    additives: ["E322"],
    allergens: ["gluten", "soybeans"],
    labels: [],
    analysisTags: ["vegetarian", "palm-oil"],
    originCountry: "de",
    packaging: ["cardboard", "plastic"],
    novaGroup: 4,
  }),
  P({
    barcode: "4012345678932",
    name: "Alpenvollmilch-Schokolade",
    brand: "Kakaowerk",
    quantity: "100 g",
    category: "chocolate",
    ingredientsText:
      "Zucker, Kakaobutter, Vollmilchpulver, Kakaomasse, Haselnussmasse, Emulgator: Sojalecithine, Aroma. Kakao: 30 % mindestens.",
    ingredients: [
      { name: "Zucker" },
      { name: "Kakaobutter" },
      { name: "Vollmilchpulver" },
      { name: "Kakaomasse" },
      { name: "Haselnussmasse" },
    ],
    nutriments: { energyKcal: 533, fat: 31, satFat: 19, carbs: 56, sugars: 54, protein: 7, salt: 0.2, fiber: 2.1 },
    additives: ["E322"],
    allergens: ["milk", "soybeans", "nuts"],
    labels: [],
    analysisTags: ["vegetarian", "palm-oil-free"],
    originCountry: "unknown",
    packaging: ["composite"],
    novaGroup: 4,
  }),
  P({
    barcode: "4012345678949",
    name: "Edelbitter 85 % Bio",
    brand: "Kakaowerk",
    quantity: "100 g",
    category: "chocolate",
    ingredientsText:
      "Kakaomasse*, Kakaobutter*, Rohrzucker*, Bourbon-Vanille*. Kakao: 85 % mindestens. *aus fairem, biologischem Anbau (Peru)",
    ingredients: [
      { name: "Kakaomasse", percent: 70 },
      { name: "Kakaobutter", percent: 15 },
      { name: "Rohrzucker", percent: 14 },
      { name: "Bourbon-Vanille" },
    ],
    nutriments: { energyKcal: 579, fat: 46, satFat: 27, carbs: 24, sugars: 14, protein: 9.5, salt: 0.02, fiber: 14 },
    additives: [],
    allergens: [],
    labels: ["organic", "fairtrade"],
    analysisTags: ["vegan", "vegetarian", "palm-oil-free"],
    originCountry: "pe",
    packaging: ["cardboard"],
    novaGroup: 3,
  }),
  P({
    barcode: "4012345678956",
    name: "Cola Classic",
    brand: "Sprudelquell",
    quantity: "1 l",
    category: "beverages",
    ingredientsText:
      "Wasser, Zucker, Kohlensäure, Farbstoff: E 150d, Säuerungsmittel: Phosphorsäure, natürliches Aroma, Koffein",
    ingredients: [
      { name: "Wasser" },
      { name: "Zucker" },
      { name: "Kohlensäure" },
      { name: "Farbstoff E 150d" },
      { name: "Phosphorsäure" },
      { name: "Koffein" },
    ],
    nutriments: { energyKcal: 42, fat: 0, satFat: 0, carbs: 10.6, sugars: 10.6, protein: 0, salt: 0, fiber: 0 },
    additives: ["E150D", "E338"],
    allergens: [],
    labels: [],
    analysisTags: ["vegan", "vegetarian", "palm-oil-free"],
    originCountry: "de",
    packaging: ["plastic"],
    novaGroup: 4,
  }),
  P({
    barcode: "4012345678963",
    name: "Cola Zero",
    brand: "Sprudelquell",
    quantity: "1 l",
    category: "beverages",
    ingredientsText:
      "Wasser, Kohlensäure, Farbstoff: E 150d, Säuerungsmittel: Phosphorsäure, Süßungsmittel: Aspartam, Acesulfam K, natürliches Aroma, Koffein",
    ingredients: [
      { name: "Wasser" },
      { name: "Kohlensäure" },
      { name: "Farbstoff E 150d" },
      { name: "Phosphorsäure" },
      { name: "Aspartam" },
      { name: "Acesulfam K" },
      { name: "Koffein" },
    ],
    nutriments: { energyKcal: 0.3, fat: 0, satFat: 0, carbs: 0, sugars: 0, protein: 0, salt: 0.02, fiber: 0 },
    additives: ["E150D", "E338", "E950", "E951"],
    allergens: [],
    labels: [],
    analysisTags: ["vegan", "vegetarian", "palm-oil-free"],
    originCountry: "de",
    packaging: ["plastic"],
    novaGroup: 4,
  }),
  P({
    barcode: "4012345678970",
    name: "Bio Hafer Drink",
    brand: "Naturkind",
    quantity: "1 l",
    category: "plant-drink",
    ingredientsText: "Wasser, Hafer* (10 %), Sonnenblumenöl*, Meersalz. *aus kontrolliert ökologischem Anbau",
    ingredients: [
      { name: "Wasser" },
      { name: "Hafer", percent: 10 },
      { name: "Sonnenblumenöl" },
      { name: "Meersalz" },
    ],
    nutriments: { energyKcal: 46, fat: 1.5, satFat: 0.2, carbs: 6.9, sugars: 4.1, protein: 1.0, salt: 0.09, fiber: 1.4 },
    additives: [],
    allergens: ["gluten"],
    labels: ["organic"],
    analysisTags: ["vegan", "vegetarian", "palm-oil-free"],
    originCountry: "de",
    packaging: ["composite"],
    novaGroup: 3,
  }),
  P({
    barcode: "4012345678987",
    name: "Erdnussmus Crunchy",
    brand: "NussWerk",
    quantity: "250 g",
    category: "spreads",
    ingredientsText: "Erdnüsse geröstet (99,5 %), Meersalz",
    ingredients: [
      { name: "Erdnüsse geröstet", percent: 99.5 },
      { name: "Meersalz" },
    ],
    nutriments: { energyKcal: 614, fat: 50, satFat: 7.2, carbs: 11.6, sugars: 5.7, protein: 29.6, salt: 0.4, fiber: 8.1 },
    additives: [],
    allergens: ["peanuts"],
    labels: [],
    analysisTags: ["vegan", "vegetarian", "palm-oil-free"],
    originCountry: "ar",
    packaging: ["glass"],
    novaGroup: 3,
  }),
  P({
    barcode: "4012345678994",
    name: "Paprika-Chips",
    brand: "Knusperland",
    quantity: "175 g",
    category: "snacks",
    ingredientsText:
      "Kartoffeln, Sonnenblumenöl, Paprika-Gewürzzubereitung (Zucker, Salz, Paprikapulver, Zwiebelpulver, Geschmacksverstärker: Mononatriumglutamat, Säuerungsmittel: Citronensäure, Aroma)",
    ingredients: [
      { name: "Kartoffeln" },
      { name: "Sonnenblumenöl" },
      { name: "Paprika-Gewürzzubereitung" },
    ],
    nutriments: { energyKcal: 528, fat: 33, satFat: 2.8, carbs: 49, sugars: 2.6, protein: 6, salt: 1.9, fiber: 4.3 },
    additives: ["E621", "E330"],
    allergens: [],
    labels: [],
    analysisTags: ["vegetarian", "palm-oil-free"],
    originCountry: "de",
    packaging: ["composite"],
    novaGroup: 4,
  }),
  P({
    barcode: "4012345679007",
    name: "Joghurt Natur 3,8 %",
    brand: "Alpgut",
    quantity: "500 g",
    category: "yogurt",
    ingredientsText: "Pasteurisierte Milch, Joghurtkulturen",
    ingredients: [{ name: "Pasteurisierte Milch" }, { name: "Joghurtkulturen" }],
    nutriments: { energyKcal: 67, fat: 3.8, satFat: 2.5, carbs: 4.7, sugars: 4.7, protein: 3.9, salt: 0.15, fiber: 0 },
    additives: [],
    allergens: ["milk"],
    labels: [],
    analysisTags: ["vegetarian", "palm-oil-free"],
    originCountry: "at",
    packaging: ["glass"],
    novaGroup: 1,
  }),
  P({
    barcode: "4012345679014",
    name: "Spaghetti N° 5",
    brand: "PastaFina",
    quantity: "500 g",
    category: "pasta",
    ingredientsText: "Hartweizengrieß, Wasser",
    ingredients: [{ name: "Hartweizengrieß" }, { name: "Wasser" }],
    nutriments: { energyKcal: 359, fat: 1.5, satFat: 0.3, carbs: 72, sugars: 3.5, protein: 12.5, salt: 0.01, fiber: 3 },
    additives: [],
    allergens: ["gluten"],
    labels: [],
    analysisTags: ["vegan", "vegetarian", "palm-oil-free"],
    originCountry: "it",
    packaging: ["cardboard"],
    novaGroup: 1,
  }),
];

export async function seedProducts(driver: Driver): Promise<void> {
  for (const data of SEED_PRODUCTS) {
    const scores = computeScores(data);
    await driver.query(
      `INSERT INTO products (barcode, name, brand, category, data, scores, score_version, source, verified)
       VALUES ($1, $2, $3, $4, $5, $6, $7, 'seed', true)
       ON CONFLICT (barcode) DO NOTHING`,
      [data.barcode, data.name, data.brand, data.category, JSON.stringify(data), JSON.stringify(scores), SCORE_VERSION]
    );
  }
}
